### ISSUE TITLE
Dte.Boletas_EnviarRCOF no funciona en ambiente certificacion

### ISSUE THREAD

**Issue by tuxerowned** [LibreDTE/libredte-modulo-Dte#10]
el problema es que funciona bien si el ambiente es Produccion donde por defecto $certificacion es 0, pero al pasar el argumento certificacion en 1, se traduce en que el segundo argumento en vez de $dia es $certificacion entonces, no hace nada.
  
si se invierte $certificacion y $dia funciona sin problemas. 

Sugerencia de parche. 

diff EnviarRCOF.php

```

43c43
<     public function main($grupo = 'dte_plus', $dia = null, $certificacion = 0, $uri = null, $filename = 'rcof_{rut}_{dia}.xml')
---
>     public function main($grupo = 'dte_plus', $certificacion = 0, $dia = null, $uri = null, $filename = 'rcof_{rut}_{dia}.xml')

```
Saludos.

**Comment by estebandelaf** [comment]
Es el comportamiento normal. Para usar en certificación ejecutar indicando la fecha en 0 así:

`$ ./shell.php Dte.Boletas_EnviarRCOF dte_plus 0 1 -v --dev`
