### ISSUE TITLE
Timbre electrónico encima de tabla de productos (PDF)

### ISSUE THREAD

**Issue by cfficaurzua** [LibreDTE/libredte-modulo-Dte#11]
Cuando hay muchos productos, el timbre queda sobre la tabla [pdf tamaño carta]
![image](https://user-images.githubusercontent.com/13381072/87474601-54e05680-c5f1-11ea-9997-ce6806e518c1.png)

**Comment by estebandelaf** [comment]
Es el comportamiento esperado. En ese caso, si son muchos items. Se debe usar papel contínuo y no hoja carta. Ya que no se puede hacer un DTE en más de una hoja.
