### ISSUE TITLE
View Helper Paginator en Dte/View/DteIntercambios/listar.php

### ISSUE THREAD

**Issue by ffigueroa** [LibreDTE/libredte-modulo-Dte#9]
Estuve revisando el repo de sowerphp y este no tiene la clase View_Helper_Paginator

Fatal error: Class 'sowerphp\app\View_Helper_Paginator' not found in /webapp/website/Module/Dte/View/DteIntercambios/listar.php on line 96

Saludos!

**Comment by estebandelaf** [comment]
El archivo si existe: https://github.com/SowerPHP/extension-app/blob/master/View/Helper/Paginator.php

Probablemente tienes o a) mal instalado o b) no actualizado.

**Comment by ffigueroa** [comment]
Correcto, estaba viendo el repo de sowerphp, no vi que tenia extensiones. Mi error 😔
